name: Multi-step workflow
on: [push]

jobs:
  steps-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello, Good morning all"
      - run: pwd
      - run: ls -la
      - run: date
