name: Multi-job pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Building project....."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Deploying project....."
